backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "photos"
    label: "Photos"
    folder: "src/pages/photos"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "photo-upload"}
      - {label: "Photo Submitted By", name: "title", widget: "string"}
      - {label: "Date Photo Taken", name: "dateTaken", widget: "datetime"}
      - {label: "Published Date", name: "datePublished", widget: "datetime"}
      - {label: "Image URL", name: "imageSource", widget: "string"}